config/routes.rb
Rails.application.routes.draw do
  #Home
  root 'home#index'

  get "/login" => "session#new"
  post "/login" => "session#create"
  get "/log-out" => "session#destroy", as: :log_out

  resources 'home', only: :index


  resources :users, only: [:index, :new, :create, :show, :edit, :update] do
    member do
      post :attack
    end
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :stat_type, presence: true
  attr_accessor :stat_sum
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessor :army_size
  attr_accessor :gold_production
  attr_accessor :attack
  attr_accessor :defense
  attr_accessor :covert

  validates :username, :email, presence: true
  validates_confirmation_of :password

  before_save :encrypt_password


  def army_size
    army_size = self.untrained + self.trained + self.spy
  end

  def gold_production
    gold_production = self.untrained * 500
  end

  def upgrades(type, index)
    if (type == true)
      upgrades = [{ "'Mud' projectiles" => 250000},{"Fire-Arrows" => 500000}, {"Medium Rocks" => 1000000}, {"Catapults"=> 5000000}, {"Rapid-Fire Ballista"=> 10000000}, {"Hand of God"=>25000000}]
    else
      upgrades = [{ "Wooden Paliside" => 250000},{"Small Trench" => 500000}, {"" => 1000000}, {"Large Trench and Drawbridge"=> 5000000}, {"Massive Reinforced Walls"=> 10000000}, {"Impenetrable Walls"=>25000000}]
    end
    debugger;
    return upgrades[index]
  end

  def attack
    sum_attack = 1
    attack = (((self.trained * 2) * sum_attack) + ((self.untrained * 1) * sum_attack) * self.attack_level)
  end

  def increase_attack_level
    if self.total_gold > upgrades(true ,self.attack_level)
      self.total_gold = self.total_gold - upgrades(self.attack_level)
      self.attack_level = self.attack_level + 1
    end
  end

  def defense
    defense = ((self.trained * 3) + (self.untrained * 1) * self.defense_level)
  end

  def covert
    covert = (self.spy * self.spy_level)
  end

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all()
  end

  def new
    @user = User.new()
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if (Integer(user_params[:trained]) + Integer(user_params[:spy]) > @user.untrained)
      puts 'exited -- Too many units'
      redirect_to edit_user_path(@user) and return
    end
    temp_params = {untrained: 0, trained: (@user.trained + Integer(user_params[:trained])), spy: (@user.spy + Integer(user_params[:spy]))}
    temp_params[:untrained] = @user.untrained - (Integer(user_params[:trained]) + Integer(user_params[:spy]))
    @user.update(temp_params)
    redirect_to edit_user_path(@user)
  end

  def attack
    @you = current_user
    @target = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :trained, :untrained, :spy)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/home/index.html.erb
<% if current_user %>

  <div class="row">
    Current:<%= current_user %> <br>
    Session: <%= session[:user_id] %>
    <hr>
    Basic Stats:
    <div class="container">
      Attack: <%= current_user.attack %> (# rank)<br>
      Defense: <%= current_user.defense %> (# rank)<br>
      Covert: <%= current_user.covert %> (# rank)<br>

      Units per Turn: <%= current_user.unit_production %><br>
      Gold Income per Turn: <%= current_user.gold_production %><br>

      Turns: <%= current_user.turns %><br>
      Gold: <%= current_user.total_gold %><br>
    </div>

    Upgrades:
    <div class="container">
      Attack_Upgrade: <%= current_user.attack_level %><br>
      Defense_Upgrade: <%= current_user.defense_level %><br>
      Covert_Upgrade: <%= current_user.spy_level %>
    </div>
  </div>

  <div class="row">
    <u>Items: </u><br>
    None atm
  </div>
<% else %>
  Hi
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KingsOfChaos Reborn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class='row'>
        <h1> <%= link_to 'KoC Reborn', root_path %> </h1>
    </div>
    <nav>
      <div class="row">
        <div class="left">
          <!-- Always show a home link -->

          <% if session[:user_id] %>
            <%= link_to current_user.username, user_path(current_user) %>
            <%= link_to 'Log Out', log_out_path %>

          <% else %>
            <%= link_to 'Log In', login_path %>
            <%= link_to 'Sign Up', new_user_path() %>
          <% end %>
        </div>
        <div class="right">
          <% if session[:user_id] %>
            <%= User.find(session[:user_id]).username %>
          <% end %>
        </div>
      </div>
      <hr>
      <% if current_user %>
        <div class="row sub_nav">
          <!-- Sub-nav -->
          <!-- Convert to dropdown eventually? -->
          <%= link_to 'Attack', users_path() %>
          <%= link_to 'Shop', edit_user_path(current_user) %>
          Logs

        </div>
      <% end %>
    </nav>
  </header>
<div class="container" style="margin: 10px;">
  <%= yield %>
</div>

</body>
</html>

app/views/session/new.html.erb
<%= form_tag login_path do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= text_field_tag :password %>

  <%= submit_tag "Log In" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/users/_training.html.erb
Train Units:
  Train "untrained" units into spies or trained soldiers.

<%= form_for @user do |f| %>
  <%= f.label "Type" %>
  <%= f.label "Current #" %>
  <%= f.label "Number to Train" %><br>

  <%= f.label :untrained %>
  <%= f.label :untrained, value: @user.untrained %><br>

  <%= f.label :trained %>
  <%= f.label @user.trained %>
  <input name="user[trained]" value=0><br>

  <%= f.label :spy %>
  <%= f.label @user.spy %>
  <input name="user[spy]" value=0><br>

  <%= f.submit 'Train Units' %>
<% end  %>

app/views/users/edit.html.erb
<head>
  <%= javascript_include_tag 'user' %>
</head>

<!-- Upgrades List panel (collapsed)  -->
<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading">
      <h3 class="panel-title">
        <a data-toggle="collapse" data-target="#upgrades_list" href="#upgrades_list" class="collapsed">Upgrades List</a>
      </h3>
    </div>
    <div id="upgrades_list" class="panel-collapse collapse">
      <p>
        <u>Attack Upgrades</u>
        <ul>
          <li>Attack Upgrade 1 Placeholder</li>
          <li>Attack Upgrade 2 Placeholder</li>
           . . .
        </ul>
        <u>Defense Upgrades</u>
        <ul>
          <li>Defense Upgrade 1 Placeholder</li>
          <li>Defense Upgrade 2 Placeholder</li>
           . . .
        </ul>

        <u>Spy Upgrades</u>
        <ul>
          <li>Covert Upgrade 1 Placeholder</li>
          <li>Covert Upgrade 2 Placeholder</li>
           . . .
        </ul>
      </p>
    </div>
  </div>
</div>

<!-- Training List panel (collapsed)  -->
<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading">
      <h3 class="panel-title">
        <a data-toggle="collapse" data-target="#training_list" href="#training_list" class="collapsed">Training List</a>
      </h3>
    </div>
    <div id="training_list" class="panel-collapse collapse">
      <p>
        <u>Train Some Units</u>
        <%= render 'training' %>
      </p>
    </div>
  </div>

</div>
<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading">
      <h3 class="panel-title">
        <a data-toggle="collapse" data-target="#Items_list" href="#Items_list" class="collapsed">Items List</a>
      </h3>
    </div>
    <div id="Items_list" class="panel-collapse collapse">
      <p>
        <u>Attack</u>
        <li>Weakest item - base attack - gold cost [ amount to purchase ]</li>
        <li>2nd weakest item - base attack - gold cost [ amount to purchase]</li>
        . . .
        <li>strongest item - base attack - gold cost [ amount to purchase]</li>
        -------------------------------------------------------------<br>
        Total cost of this purchase:      [total_cost]
      </p>
      <p>
        <u>Defense</u>
        <li>Weakest item - base defense - gold cost [ amount to purchase ]</li>
        <li>2nd weakest item - base defense - gold cost [ amount to purchase]</li>
        . . .
        <li>strongest item - base defense - gold cost [ amount to purchase]</li>
        -------------------------------------------------------------<br>
        Total cost of this purchase:      [total_cost]
      </p>

    </div>
  </div>

</div>

app/views/users/index.html.erb
<body>
  <h1>
    Attack Page
  </h1>

  <% if @users.any? %>
    <div class="row">
      Rank [WiP] - Username  - - - Army Size - - - Current Gold
    </div>
    <% @users.each do |user| %>
    <div class="row">
      =Rank= - <%= link_to user.username, user_path(user) %> <%= link_to '[Attack]', attack_user_path(user), method: 'post', locals: {session[:attack_turns] = 15} %> [spy] [sabotage] - - - <%= user.army_size %> - - - <%= user.total_gold %>
    </div>
    <% end %>
  <% end %>
</body>

app/views/users/new.html.erb
<%= render 'form' %>